//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public long id { get; set; }
        public string taskType { get; set; }
        public string projectId { get; set; }
        public string projectName { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
        public Nullable<System.TimeSpan> fromTime { get; set; }
        public Nullable<System.TimeSpan> toTime { get; set; }
        public Nullable<decimal> hours { get; set; }
        public string remarks { get; set; }
        public string projectStatus { get; set; }
        public string status { get; set; }
        public string resourceId { get; set; }
        public string resourceName { get; set; }
        public Nullable<System.DateTime> submittedOn { get; set; }
        public Nullable<System.DateTime> approvedOn { get; set; }
        public string approvedBy { get; set; }
        public string approvalRemark { get; set; }
        public string category { get; set; }
        public string subCategory { get; set; }
        public string CRNumber { get; set; }
        public string supportTicketId { get; set; }
        public string BusinessUserName { get; set; }
        public string TimeSheetId { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        public virtual projectMaster projectMaster { get; set; }
    }
}
