//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectTrackerV2Entities : DbContext
    {
        public ProjectTrackerV2Entities()
            : base("name=ProjectTrackerV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<approverResourceMapping> approverResourceMappings { get; set; }
        public virtual DbSet<expDelDate> expDelDates { get; set; }
        public virtual DbSet<projectMaster> projectMasters { get; set; }
        public virtual DbSet<projectRemark> projectRemarks { get; set; }
        public virtual DbSet<roleMaster> roleMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<userMaster> userMasters { get; set; }
        public virtual DbSet<userRoleMapping> userRoleMappings { get; set; }
        public virtual DbSet<vendorMaster> vendorMasters { get; set; }
        public virtual DbSet<projectStatu> projectStatus { get; set; }
    }
}
