//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class userMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userMaster()
        {
            this.approverResourceMappings = new HashSet<approverResourceMapping>();
            this.approverResourceMappings1 = new HashSet<approverResourceMapping>();
            this.userRoleMappings = new HashSet<userRoleMapping>();
            this.approverResourceMappings2 = new HashSet<approverResourceMapping>();
        }
    
        public long id { get; set; }
        public string userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailId { get; set; }
        public string vendorId { get; set; }
        public string vendorName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdTimeStamp { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approverResourceMapping> approverResourceMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approverResourceMapping> approverResourceMappings1 { get; set; }
        public virtual vendorMaster vendorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userRoleMapping> userRoleMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approverResourceMapping> approverResourceMappings2 { get; set; }
    }
}
